'use client'

import { useState, useEffect, useCallback } from 'react'
import { Moon, ChevronDown, ChevronUp } from 'lucide-react'
import { useOrg } from '@/lib/org-context'
import { authFetch } from '@/lib/supabase'

const API_URL = process.env.NEXT_PUBLIC_API_URL!

interface NightReportData {
  id: string
  generated_at: string
  summary: string
  highlights: string[]
  alerts: string[]
  score_delta: number
}

/**
 * Night Report — Daily briefing card.
 * Shows the latest automated summary generated by QStash job at 7AM COL.
 * Available all day until the next report is generated.
 * Data comes from interaction_logs (event_type=DAILY_REPORT).
 */

async function fetchNightReport(orgId: string, branchId?: string | null): Promise<NightReportData | null> {
  try {
    const url = branchId
      ? `${API_URL}/analytics/${orgId}/night-report?branch_id=${branchId}`
      : `${API_URL}/analytics/${orgId}/night-report`
    const res = await authFetch(url)
    if (!res.ok) return null
    const data = await res.json()
    // Backend returns null if no report exists
    if (!data || !data.id) return null
    return data
  } catch {
    return null
  }
}

export function NightReport() {
  const { orgId, branchId } = useOrg()
  const [report, setReport] = useState<NightReportData | null>(null)
  const [expanded, setExpanded] = useState(false)
  const [loading, setLoading] = useState(true)

  const load = useCallback(async () => {
    setLoading(true)
    const data = await fetchNightReport(orgId, branchId)
    setReport(data)
    setLoading(false)
  }, [orgId, branchId])

  useEffect(() => { load() }, [load])

  // Show a placeholder when no report exists (new clinic / first day)
  if (loading) {
    return (
      <div className="glass-card p-4 animate-pulse">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-surface-3" />
          <div className="h-4 bg-surface-3 rounded w-40" />
        </div>
      </div>
    )
  }

  if (!report) {
    return (
      <div className="glass-card p-4 flex items-center gap-3">
        <div className="w-8 h-8 rounded-lg bg-brand-purple/8 border border-brand-purple/15 flex items-center justify-center flex-shrink-0">
          <Moon size={16} className="text-brand-purple" />
        </div>
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-mono font-bold text-text-dim uppercase tracking-[0.15em]">Night Report</span>
          </div>
          <p className="text-xs font-mono text-text-dim">
            Tu primer reporte nocturno se genera manana a las 7AM.
          </p>
        </div>
      </div>
    )
  }

  const reportTime = new Date(report.generated_at).toLocaleTimeString(undefined, {
    hour: '2-digit',
    minute: '2-digit',
  })

  return (
    <div className="glass-card p-4">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center gap-3 cursor-pointer group"
      >
        <div className="w-8 h-8 rounded-lg bg-brand-purple/8 border border-brand-purple/15 flex items-center justify-center flex-shrink-0">
          <Moon size={16} className="text-brand-purple" />
        </div>
        <div className="flex-1 min-w-0 text-left">
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-mono font-bold text-brand-purple uppercase tracking-[0.15em]">Night Report</span>
            <span className="text-[9px] font-mono text-text-dim">{reportTime}</span>
            {report.score_delta !== 0 && (
              <span className={`text-[10px] font-mono font-bold ${report.score_delta > 0 ? 'text-status-success' : 'text-status-danger'}`}>
                {report.score_delta > 0 ? '+' : ''}{report.score_delta}
              </span>
            )}
          </div>
          <p className={`text-xs font-mono text-text-muted ${expanded ? '' : 'truncate'}`}>{report.summary}</p>
        </div>
        <div className="flex-shrink-0 text-text-dim group-hover:text-text-muted transition-colors">
          {expanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
        </div>
      </button>

      {expanded && (
        <div className="mt-3 pt-3 border-t border-border space-y-3 animate-fade-in">
          {report.highlights.length > 0 && (
            <div>
              <span className="text-[10px] font-mono font-bold text-text-dim uppercase tracking-wider">Highlights</span>
              <ul className="mt-1.5 space-y-1">
                {report.highlights.map((h, i) => (
                  <li key={i} className="text-xs font-mono text-text-secondary flex items-start gap-2">
                    <span className="text-brand-purple mt-0.5">+</span>
                    {h}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {report.alerts.length > 0 && (
            <div>
              <span className="text-[10px] font-mono font-bold text-text-dim uppercase tracking-wider">Alertas</span>
              <ul className="mt-1.5 space-y-1">
                {report.alerts.map((a, i) => (
                  <li key={i} className="text-xs font-mono text-status-warning flex items-start gap-2">
                    <span className="mt-0.5">!</span>
                    {a}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
