'use client'

import { useState, useEffect, useCallback } from 'react'
import { Moon, ChevronDown, ChevronUp } from 'lucide-react'
import { useOrg } from '@/lib/org-context'

interface NightReportData {
  id: string
  generated_at: string
  summary: string
  highlights: string[]
  alerts: string[]
  score_delta: number
}

/**
 * Night Report — 8AM briefing card.
 * Shows the latest automated overnight summary.
 * Data comes from the night_reports table (generated by QStash job).
 * Gracefully degrades if no report exists yet.
 */

async function fetchNightReport(orgId: string): Promise<NightReportData | null> {
  try {
    const res = await fetch(`/api/night-report?org_id=${orgId}`)
    if (!res.ok) return null
    return res.json()
  } catch {
    return null
  }
}

export function NightReport() {
  const { orgId } = useOrg()
  const [report, setReport] = useState<NightReportData | null>(null)
  const [expanded, setExpanded] = useState(false)
  const [loading, setLoading] = useState(true)

  const load = useCallback(async () => {
    setLoading(true)
    const data = await fetchNightReport(orgId)
    setReport(data)
    setLoading(false)
  }, [orgId])

  useEffect(() => { load() }, [load])

  // Show a placeholder when no report exists (new clinic / first day)
  if (loading) {
    return (
      <div className="glass-card p-3 animate-pulse">
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-md bg-surface-3" />
          <div className="h-3 bg-surface-3 rounded w-32" />
        </div>
      </div>
    )
  }

  if (!report) {
    return (
      <div className="glass-card p-3 flex items-center gap-2.5">
        <div className="w-6 h-6 rounded-md bg-brand-purple/8 border border-brand-purple/15 flex items-center justify-center flex-shrink-0">
          <Moon size={12} className="text-brand-purple" />
        </div>
        <div className="min-w-0">
          <div className="flex items-center gap-1.5">
            <span className="text-[8px] font-mono font-bold text-text-dim uppercase tracking-[0.15em]">Night Report</span>
          </div>
          <p className="text-[9px] font-mono text-text-dim">
            Tu primer reporte nocturno se genera manana a las 8AM.
          </p>
        </div>
      </div>
    )
  }

  const reportTime = new Date(report.generated_at).toLocaleTimeString(undefined, {
    hour: '2-digit',
    minute: '2-digit',
  })

  return (
    <div className="glass-card p-3">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center gap-2.5 cursor-pointer group"
      >
        <div className="w-6 h-6 rounded-md bg-brand-purple/8 border border-brand-purple/15 flex items-center justify-center flex-shrink-0">
          <Moon size={12} className="text-brand-purple" />
        </div>
        <div className="flex-1 min-w-0 text-left">
          <div className="flex items-center gap-1.5">
            <span className="text-[8px] font-mono font-bold text-brand-purple uppercase tracking-[0.15em]">Night Report</span>
            <span className="text-[7px] font-mono text-text-dim">{reportTime}</span>
            {report.score_delta !== 0 && (
              <span className={`text-[8px] font-mono font-bold ${report.score_delta > 0 ? 'text-status-success' : 'text-status-danger'}`}>
                {report.score_delta > 0 ? '+' : ''}{report.score_delta}
              </span>
            )}
          </div>
          <p className="text-[9px] font-mono text-text-muted truncate">{report.summary}</p>
        </div>
        <div className="flex-shrink-0 text-text-dim group-hover:text-text-muted transition-colors">
          {expanded ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
        </div>
      </button>

      {expanded && (
        <div className="mt-2.5 pt-2.5 border-t border-border space-y-2 animate-fade-in">
          {report.highlights.length > 0 && (
            <div>
              <span className="text-[8px] font-mono font-bold text-text-dim uppercase tracking-wider">Highlights</span>
              <ul className="mt-1 space-y-0.5">
                {report.highlights.map((h, i) => (
                  <li key={i} className="text-[9px] font-mono text-text-secondary flex items-start gap-1.5">
                    <span className="text-brand-purple mt-0.5">+</span>
                    {h}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {report.alerts.length > 0 && (
            <div>
              <span className="text-[8px] font-mono font-bold text-text-dim uppercase tracking-wider">Alertas</span>
              <ul className="mt-1 space-y-0.5">
                {report.alerts.map((a, i) => (
                  <li key={i} className="text-[9px] font-mono text-status-warning flex items-start gap-1.5">
                    <span className="mt-0.5">!</span>
                    {a}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
